var length = prompt("Enter length");
length = parseFloat(length);
var width = prompt("Enter width");
width = parseFloat(width);
document.write("Length = " + length);
document.write("<br>");
document.write("Width = " + width);
document.write("<br>");
document.write("<br>");
document.write("Area = " + length * width);
document.write("<br>");
document.write("Perimeter = " + (2 * length + 2 * width));
document.write("<br>");
document.write("<br>");